### ISSUE TITLE
Bugs in RTSPClient.java

### ISSUE THREAD

**Issue by ch08532** [opensensorhub/osh-sensors#7]
I've been successful getting a connection to the AXIS camera (AXIS Q6115-E Network Camera) RTSP feed working (it uses GStreamer RTSP server).  I am able to at least get the video streaming via getResults but it seems to only play several seconds then stops (that's a separate issue).  Nonetheless, I have made changes to my local feature branch to get RTSP connected up:

1) Sending REQ_OPTIONS with a Session Id of "0" returns an error from GStreamer.  I had to change sendRequest to not send Session Id if it's "0".  

```
else { 
            // otherwise, write the Session ID
            if (rtspSessionID != "0") {
             rtspRequestWriter.write("Session: " + rtspSessionID + CRLF);
            
            }
   }
```

2)  GStreamer sends parameter fmtp:96 with a few semi-colon delimited attributes:

` a=fmtp:96 packetization-mode=1;profile-level-id=4d0029;sprop-parameter-sets=Z00AKeKQCgC3YC3AQEB4eJEV,aO48gA==`

You will notice that there is no space between these attributes.  However, in the code it looks for a` "; "` to split the line (line 446).  The fix is to remove the space.  Without this fix the video frames would never get assembled and send onto the dbus via the callback.

```
for (String token: line.split(";"))
                        {
                            if (token.startsWith("sprop-parameter-sets"))
                            {
                               
                                stream.paramSets = token.substring(token.indexOf('=')+1).trim();
                                break;
                            }
                        }
```

**Comment by mikebotts** [comment]
Hi ch0832.

You’ve been working pretty hard. I hope you’re getting all the answers you need. Don’t hesitate to keep reminding us if you don't get answers when you need them.

Are you able and willing to identify yourself or do you wish to stay anonymous. Either is OK. We just appreciate your help and interest.

Thanks.
Mike Botts

Dr. Mike Botts
Botts Innovative Research, Inc.
http://www.botts-inc.com
http://opensensorhub.org
mike.botts@botts-inc.com

**Comment by ch08532** [comment]
Hi Mike,,

Thanks for the offering (no pun intended) :) So far everyone has been helpful.

I've been enjoying this project as of late simply because this is the first open source project that really leverages OGC SOS, SWE services and does it well and respects the standards.  Probably the best implementation out there that isn't engineer centric. I've seen implementations where users need to truly understand the specification to connect the dots.  This one is pretty good. Clearly there was a lot of effort in this project.

Cheers!

Chris

**Comment by alexrobin** [comment]
Thanks for your comment on OSH Chris and thanks for the fix.
I'll try to integrate that into master ASAP. Do you want to do an officiel Pull Request so we can retain you as the author of the fix?

**Comment by ch08532** [comment]
Yes please if you can create a PR that would be perfect.  Thanks

**Comment by alexrobin** [comment]
Actually you are the one who has to initiate the PR. First pull the latest from the osh-core repo then commit and push your fix to your own OSH fork on GitHub, then create a PR against the opensensorhub/osh-core repo. See https://help.github.com/articles/about-pull-requests/
Thanks

**Comment by ch08532** [comment]
Ok thanks.  I was having issues creating the remote branch and assumed it was a permission issue on the repo.  I will double check the configuration on my end.  Thanks

**Comment by ch08532** [comment]
PR created.

**Comment by mikebotts** [comment]
Chris. Your pul request has been merged so I'm assuming that your pull request fixed the issues above although that wasn't clear from your initial statement. Does the video still stop aftr 10 seconds with these fixes?  Thanks.
